# https://docs.spring.io/spring-cloud-stream/reference/rabbit/rabbit_overview/putting-it-all-together.html#page-title
configs:
  amqp:
    bindings:
      tbd: ${A6_PROJECTS_MGMT_INTEGRATIONS_RABBITMQ_BINDINGS_TBD:tbd}

spring:
  cloud:
    stream:
      bindings:
        createContributorAccountsForMgmt-in-0:
          destination: ${A6_PROJECTS_MGMT_ACCOUNTING_RABBITMQ_CREATEACCOUNTSFORMGMT_INPUT_EXCHANGE:projectManagement} # existing exchange (or creates)?
          group: ${A6_PROJECTS_MGMT_ACCOUNTING_RABBITMQ_CREATEACCOUNTSFORMGMT_INPUT_QUEUE:contributorRegistered}
          binder: a6Rabbit
      rabbit:
        bindings:
          createContributorAccountsForMgmt-in-0:
            consumer:
              republishToDlq: false
      binders:
        a6Rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: ${A6_MGMT_ACCOUNTING_RABBITMQ_HOST:localhost}
                port: ${A6_MGMT_ACCOUNTING_RABBITMQ_PORT:5672}
                username: ${A6_MGMT_ACCOUNTING_RABBITMQ_USER:guest}
                password: ${A6_MGMT_ACCOUNTING_RABBITMQ_PASSWORD:guest}
                virtual-host: ${A6_MGMT_ACCOUNTING_RABBITMQ_VHOST:/}
    function:
      definition: createContributorAccountsForMgmt