context:
  initializer:
    classes: com.angorasix.projects.management.accounting.BeansInitializer
server:
  port: ${A6_PROJECTS_MGMT_ACCOUNTING_PORT:10303}

logging:
  level:
    root: ${A6_PROJECTS_MGMT_ACCOUNTING_LOGGING_LEVEL_GENERAL:INFO}
    org.springframework.web: ${A6_PROJECTS_MGMT_ACCOUNTING_LOGGING_LEVEL_WEB:INFO}
    com.angorasix: ${A6_PROJECTS_MGMT_ACCOUNTING_LOGGING_LEVEL_ANGORASIX:INFO}
    org.springframework.data.mongodb.core: ${A6_PROJECTS_MGMT_ACCOUNTING_LOGGING_LEVEL_DATA:INFO}

spring:
  config:
    import: optional:file:config/env.properties, classpath:/api.yml, classpath:/security.yml, classpath:/amqp.yml, classpath:/axon.yml
  application:
    name: ${APP_NAME:projects.management.accounting}
  data:
    mongodb:
      uri: ${A6_PROJECTS_MGMT_ACCOUNTING_MONGO_DB_URI:mongodb://localhost:27017/}${A6_PROJECTS_MGMT_ACCOUNTING_MONGO_DB_NAME:a6-management-accounting}${A6_PROJECTS_MGMT_ACCOUNTING_MONGO_DB_PARAMS:?}
      auto-index-creation: true
